stages:
  preproc:
    cmd: python src/process.py
    deps:
    - src/config.py
    - src/process.py
    outs:
      - data/ames_processed.pkl
  data_separation:
    cmd: python src/data_separation.py
    deps:
    - data/ames_processed.pkl
    - src/data_separation.py
    outs:
    - data/processed/train.pkl
    - data/processed/test.pkl 
  train:
    cmd: python src/train.py
    deps:
    - data/processed/train.pkl
    - src/train.py
    outs:
    - models/stack_reg.pkl
  test:
    cmd: python src/test.py
    deps:
    - data/processed/test.pkl
    - models/stack_reg.pkl
    - src/test.py
